### ISSUE TITLE
Blender not importingmotion files

### ISSUE THREAD

**Issue by zap257** [davidpagnon/Pose2Sim_Blender#3]
I managed to get the following working:
![image](https://github.com/davidpagnon/Pose2Sim_Blender/assets/75625759/a5808802-f83f-4c04-b700-d83dbbc28e9c)

The .osim model is imported however, upon trying to add the motion .csv file i get the following error:

Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Pose2Sim_Blender\Pose2Sim_Blender\motion.py", line 77, in apply_mot_to_model
    collection=bpy.data.collections['osimModel']
KeyError: 'bpy_prop_collection[key]: key "osimModel" not found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Pose2Sim_Blender\__init__.py", line 304, in execute
    motion.apply_mot_to_model(mot_path, osim_path, direction='zup', target_framerate=self.target_framerate)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Pose2Sim_Blender\Pose2Sim_Blender\motion.py", line 80, in apply_mot_to_model
    raise('First import an OpenSim .osim model.')
TypeError: exceptions must derive from BaseException

Any assistance would be appreciated

**Comment by zap257** [comment]
Well, I've just commented out the try-except block at line 77 and that worked. Hope this helps whoever gets stuck on the same issue

**Comment by davidpagnon** [comment]
Hi @zap257,
I'm sorry, I just notice now that I was not subscribed to the issues! Thanks for the feedback, and sorry for being late.
